### ISSUE TITLE
Crash when I swipe two or three items quickly

### ISSUE THREAD

**Issue by hunain-liaquat** [47deg/android-swipelistview#239]
I have used a wrapper on your library for pull to refresh below  is link for that wrapper library,

https://github.com/keiththompson/SwipeListViewRefresh

following is the log for crash kindly look into it if you can help in solving this issue.
Thanks,

java.lang.ArrayIndexOutOfBoundsException: length=27; index=-1
       at java.util.ArrayList.get(ArrayList.java:310)
       at com.fortysevendeg.swipelistview.SwipeListViewTouchListener.actionUp(SwipeListViewTouchListener.java:1296)
       at com.fortysevendeg.swipelistview.SwipeRefreshListViewTouchListener.onTouch(SwipeRefreshListViewTouchListener.java:131)
       at android.view.View.dispatchTouchEvent(View.java:8465)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2399)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2092)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2369)
       at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1719)
       at android.app.Activity.dispatchTouchEvent(Activity.java:2742)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2330)
       at android.view.View.dispatchPointerEvent(View.java:8666)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4123)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3989)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3597)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3563)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3680)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3571)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3737)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3597)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3563)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3571)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5807)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5781)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5752)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5897)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:143)
       at android.os.Looper.loop(Looper.java:122)
       at android.app.ActivityThread.main(ActivityThread.java:5254)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by hunain-liaquat** [comment]
If I quickly swipe on two items, one is revealed half and try to reveal other than app crashes.
